plugins:
  project_countdown_enabled:
    default: true
    client: true
    description: "启用项目倒计时功能"
  project_countdown_show_in_header:
    default: false
    client: true
    description: "在论坛顶部显示项目倒计时组件"
  project_countdown_max_projects_per_user:
    default: 50
    min: 1
    max: 200
    description: "每个用户最多可创建的项目数量"